version: '3.9'

services:
  database:
    image: mongo:4.0.16-xenial
    ports:
      - 27017:27017    
  auth:
    build: .
    depends_on:
      - database
    ports:
      - 3000:3000    
    environment:
      - DB_URL=mongodb://database:27017